### ISSUE TITLE
Add filepointer option to openfile/analyze function

### ISSUE THREAD

**Issue by Rello** [JamesHeinrich/getID3#172] opened 2018-12-04 19:39 UTC
Hello James,

first a thank you for your super library.

I am using it in the [Audio Player](https://github.com/Rello/audioplayer) for Nextcloud/ownCloud. Same does @paulijar for the [Music](https://github.com/owncloud/music) app.

We both use a little tweak to hand over a file pointer for better performance using streams.
As we have to apply the tweak after every of your nice upgrades, I would like to ask you to review this to evaluate if you could include this from stock. It might be useful for others also.

you can see the modifications here: https://github.com/Rello/audioplayer/commit/89f6a26069bce132825548a4425dffe7c5781ebf

Please let me know what you think.
Thank you,
Rello

**Comment by JamesHeinrich** [comment] 2018-12-04 19:51
I would suggest that instead of breaking the definition of function `openfile` by inserting a new parameter between the two existing ones, add `$fp=null` as the _third_ parameter, not the second. That way any existing calls to the function will function unchanged, and only any modified calls passing `$fp` as the third parameter will use the new code.

If you want to submit the change (modified as per above) as a pull request I can merge it. Please be sure to maintain my finicky formatting standards, with a space between parameters:
`openfile($filename, null, $fp)` not `openfile($filename,null,$fp)`
and explicit logic parentheses:
no: `if ($fp != null && (get_resource_type($fp) == 'file' || get_resource_type($fp) == 'stream')) {`
yes: `if (($fp != null) && ((get_resource_type($fp) == 'file') || (get_resource_type($fp) == 'stream'))) {`

**Comment by Rello** [comment] 2018-12-04 19:53
hello,
thank you for your quick reply!

yes, as a third parameter is the prerequisite for a global change. Did not want to make my first post even bigger.

I will create a pull.
thanks and keep up with your nice work...

**Comment by Rello** [comment] 2018-12-04 20:58
Hello James,
I forgot to bump the version number.
I guess it will be _1.9.16-201812042150_ ?
will you change it? then I will include the new version right away...

**Comment by JamesHeinrich** [comment] 2018-12-04 21:15
Sure, that can be the version number. I made the version number change, wrapped into an omnibus code-formatting cleanup commit:
https://github.com/JamesHeinrich/getID3/commit/aab2924670724ea75e62ac59abb655fe365c15ee

**Comment by JamesHeinrich** [comment] 2018-12-05 06:31
This change has broken some other formats that spawn a second instance of getID3 to examine additional content inside a container (e.g. mp3 audio inside RIFF.AVI, or WavPack audio inside RIFF.WAV). I haven't yet found the cause or solution, but I'll look at it tomorrow.

**Comment by JamesHeinrich** [comment] 2018-12-05 06:44
Actually it wasn't so hard, there was an unnecessary addition of the filepointer to `openfile` under `getid3_riff::ParseRIFFdata`, the temp file opened there should always be local.
Fixed in https://github.com/JamesHeinrich/getID3/commit/f31b8961570a109b7284ead133f2d3ece4358961

**Closed by JamesHeinrich** 2018-12-05 06:44 UTC

**Comment by Rello** [comment] 2018-12-05 06:48
sorry for that. did not have this combination in my testfiles
