### ISSUE TITLE
PHP 7.4 Deprecated magic_quotes functions

### ISSUE THREAD

**Issue by SlvrEagle23** [JamesHeinrich/getID3#210] opened 2019-11-30 05:55 UTC
Hello all!

My test suite is throwing a fit at the presence of [these lines](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L297-L309) from the main `getid3` class, as simply retrieving the setting at all in the newly-released PHP 7.4 triggers a deprecation warning that it's no longer supported at all.

I'm not sure what the project would prefer as far as a solution to this, either removing the lines altogether or wrapping them in a PHP version check, but it would be good to avoid them being executed at all in 7.4 and beyond, even if the function names themselves exist.

**Comment by JamesHeinrich** [comment] 2019-11-30 12:23
Thanks, fixed in https://github.com/JamesHeinrich/getID3/commit/75454e8b19c7b1b041382b91906574fe484f605b

I also noticed there was an error in the second function, checking for the existence of _magic_quotes_gpc_ and then running _get_magic_quotes_gpc_, that's now fixed too. That may have been the cause of your test suite "throwing a fit".

**Closed by JamesHeinrich** 2019-11-30 12:23 UTC
