### ISSUE TITLE
Error in demo.mysqli.php help

### ISSUE THREAD

**Issue by romanoh** [JamesHeinrich/getID3#270] opened 2020-10-10 18:24 UTC
![imagem](https://user-images.githubusercontent.com/5342223/95662316-fe21e480-0b2d-11eb-80fe-f0dfcec07f73.png)

i am using demo.mysqli.php, and an error apears, is something i did wrong? please

looking around maybe something to do with UTF8 ?

**Comment by JamesHeinrich** [comment] 2020-10-10 19:06
I would suspect it's UTF8-related. How are the fields (especially `comments_all`) defined in your database table (`test_xml` ?)
Can you provide a `SHOW CREATE TABLE <tablename>` to show the structure?

**Comment by romanoh** [comment] 2020-10-10 19:32
`CREATE TABLE `test_xml` (
 `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `filename` text NOT NULL,
 `last_modified` int(11) NOT NULL DEFAULT 0,
 `md5_file` varchar(32) NOT NULL DEFAULT '',
 `md5_data` varchar(32) NOT NULL DEFAULT '',
 `md5_data_source` varchar(32) NOT NULL DEFAULT '',
 `filesize` int(10) unsigned NOT NULL DEFAULT 0,
 `fileformat` varchar(255) NOT NULL DEFAULT '',
 `audio_dataformat` varchar(255) NOT NULL DEFAULT '',
 `video_dataformat` varchar(255) NOT NULL DEFAULT '',
 `audio_bitrate` float NOT NULL DEFAULT 0,
 `video_bitrate` float NOT NULL DEFAULT 0,
 `playtime_seconds` varchar(255) NOT NULL DEFAULT '',
 `tags` varchar(255) NOT NULL DEFAULT '',
 `artist` varchar(255) NOT NULL DEFAULT '',
 `title` varchar(255) NOT NULL DEFAULT '',
 `remix` varchar(255) NOT NULL DEFAULT '',
 `album` varchar(255) NOT NULL DEFAULT '',
 `genre` varchar(255) NOT NULL DEFAULT '',
 `comment` text NOT NULL,
 `track` varchar(7) NOT NULL DEFAULT '',
 `comments_all` longtext NOT NULL,
 `comments_id3v2` longtext NOT NULL,
 `comments_ape` longtext NOT NULL,
 `comments_lyrics3` longtext NOT NULL,
 `comments_id3v1` text NOT NULL,
 `warning` longtext NOT NULL,
 `error` longtext NOT NULL,
 `track_volume` float NOT NULL DEFAULT 0,
 `encoder_options` varchar(255) NOT NULL DEFAULT '',
 `vbr_method` varchar(255) NOT NULL DEFAULT '',
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`

**Comment by JamesHeinrich** [comment] 2020-10-10 20:47
Could you please try adding this line around [line 48](https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.mysqli.php#L48)
`mysqli_set_charset($con, 'utf8');`
and let me know if that helps?

**Comment by romanoh** [comment] 2020-10-10 20:53
I am sorry still the same.

**Comment by JamesHeinrich** [comment] 2020-10-14 12:25
I've found the cause of the problem -- the database fields for `comments_all` (and similar) were defined as LONGTEXT which is fine most of the time, until you try inserting binary data (such as cover art) then you get errors as you did. I have changed the table definition from LONGTEXT to LONGBLOB and that should fix the problem.

Fixed in https://github.com/JamesHeinrich/getID3/commit/10bfeed3221d8d0adee8d15e918a771d971aae8b

**Closed by JamesHeinrich** 2020-10-14 12:25 UTC

**Comment by romanoh** [comment] 2020-10-14 13:21
Thank you it worked.

@JamesHeinrich also, can it put the cover art in the database, to put the image in an webpage?

**Comment by JamesHeinrich** [comment] 2020-10-14 14:16
Cover art is already included in the `comments_all` field in the database, that was the source of the error with LONGTEXT (instead of LONGBLOB). If you unserialize `comments_all` and look under `picture` you will find whatever images are available. You can look at demo.browse.php for some sample code for how to display them inline in a webpage as base64.

**Comment by romanoh** [comment] 2020-10-18 00:49
@JamesHeinrich I am sorry, i have search for 3 days, and cannot display the image in a webpage, i have tried everything, i now its not in the area of you program, just a little help please. i have tried everything: this is just some examples: https://i.imgur.com/lIhviAF.png

**Comment by JamesHeinrich** [comment] 2020-10-21 04:08
You would need to walk through the array of picture(s) that may (or may not) be present.
```
if (!empty($row['comments_all']['picture'])) {
	echo 'Found '.count($row['comments_all']['picture']).' pictures:<br>';
	foreach ($row['comments_all']['picture'] as $picturedata) {
		if (!empty($picturedata['data']) && !empty($picturedata['image_mime'])) {
			echo '<img src="data:'.$picturedata['image_mime'].';base64,'.base64_encode($picturedata['data']).'" width="'.$picturedata['image_width'].'" width="'.$picturedata['image_height'].'"><br>';
		}
	}
}
```

**Comment by romanoh** [comment] 2020-10-21 09:07
Thank you for the awnser.
But still nothing is showing. But if i put just `echo $row['comments_all'];` it shows something:

![imagem](https://user-images.githubusercontent.com/5342223/96698626-41c5eb00-1385-11eb-8ba1-ddcd780fe8d3.png)

**Comment by JamesHeinrich** [comment] 2020-10-21 15:47
Ah, yes, of course, the stored in the database is [serialized](https://www.php.net/manual/en/function.serialize.php), need to [unserialize](https://www.php.net/manual/en/function.unserialize.php) it first. I have edited my above comment to add this at the top:
```
// data is stored in database cache table using PHP's serialize function, must unserialize before using:
$row['comments_all'] = unserialize($row['comments_all']);
```

**Comment by romanoh** [comment] 2020-10-21 15:51
Thank you friend, you are wonderful.
